config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :questions
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/explore', to: 'home#explore'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  resources :mentions, only: [:index]
  resources :categories

  resources :articles do
    resources :comments, only: %w[create destroy]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  namespace :users do
    get '/:id', to: 'profile#show', as: :profile
  end

  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  has_rich_text(:content)
  belongs_to :user
  has_many :category_articles
  has_many :comments
  has_many :categories, through: :category_articles

  after_create :send_notifications

  def save_category
    if category_ids.nil? || category_ids.empty?
      return category_articles.destroy_all
    end

    category_articles.where.not(category_id: category_ids).destroy_all

    CategoryArticle.find_or_create_by(article: self, category_id: category_ids)
  end

  def send_notifications
    users = users_mentions
    users.each do |user|
      ArticleMailer.user_mention(self, user).deliver_now
    end
  end

  def users_mentions
    @users ||= content.body.attachments.select { |a| a.attachable.class == User }.map(&:attachable).uniq
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[edit new update destroy create]
  before_action :find, only: %i[edit show update destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
    @categories = Category.all
  end

  def edit
    @categories = Category.all
  end

  def show
    @comments = @article.comments
    @comment = Comment.new
  end

  def update
    @article_params = article_params
    Obscenity.sanitize @article_params[:content]
    @article.update(@article_params)
    @article.save_category
    redirect_to @article
  end

  def create
    @article_params = article_params
    Obscenity.sanitize @article_params[:content]
    @article = current_user.articles.create(@article_params)

    @article.save_category
    redirect_to @article
  end

  def destroy
    @article.categories.destroy_all
    @article.comments.destroy_all
    @article.destroy
    redirect_to root_path
  end

  private

  def find
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :category_ids)
  end
end

app/views/articles/_article.html.erb
<div class="">
  <div class="flex justify-center">
    <h2 class="text-4xl font-semibold"><%= article.title %></h2>
  </div>
  <div class="text-justify bg-white p-4 rounded-lg shadow-lg">
    <p><%= article.content %></p>
    <div class="flex justify-between m-5">
      <div class="block">
        <%= link_to users_profile_path(article.user.id) do %>
          <div class="flex text-indigo-500 hover:text-indigo-400">
              <%= gravatar_image_tag article.user.email, class:"relative z-10 block h-12 w-12 rounded-full" %>
              <span class="self-center text-current font-semibold mx-3"><%= article.user.username %></span>
          </div>
        <% end %>
      <p class="text-gray-700 self-center mt-2">
        <% if article.updated_at.to_i == article.created_at.to_i %>
          Created <span><%= time_tag article.created_at %></span>
        <% else %>
          Updated <span><%= time_tag article.updated_at %></span>
        <% end %>
      </p>
      </div>
      <div class="block">
        <% if current_user == @article.user %>
          <%=link_to "Delete Article", @article, method: :delete, class:"mt-2 mr-2 px-3 py-2 bg-indigo-500 hover:bg-indigo-400 font-semibold text-gray-100 rounded shadow-lg transition ease-in-out duration-150"%>
          <%=link_to "Edit Article", edit_article_path, class:"mt-2 px-3 py-2 bg-gray-100 hover:bg-white font-semibold text-indigo-500 rounded shadow-lg transition ease-in-out duration-150 border" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/_article_preview.html.erb
<div class="max-w-sm w-full lg:max-w-full lg:flex mb-4">
    <div class="h-48 lg:h-auto lg:w-48 flex-none bg-cover rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden" style="background-image: url(<%= image_path('header.jpg')%>)" title="Woman holding a mug">
    </div>
    <div class="border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal w-full">
      <div class="mb-8">
        <div class="inline-flex">
          <% article_preview.categories.each do |category|%>
          <p class="flex-1 text-sm text-white-600 flex items-center">
              <span class="text-700">
                <%= link_to category.title, category, class:"ml-4 rounded-full px-2 py-0.5 flex items-center text-xs leading-4 tracking-wide uppercase font-semibold text-white",  style:"background-color: " + category.color + ";"%>
              </span>
          </p>
          <% end %>
        </div>
        <div class="text-gray-900 font-bold text-xl mb-2"><%= link_to article_preview.title, article_preview %></div>
        <div class="text-gray-700 text-base">
          <%= truncate strip_tags(article_preview.content.to_s), length: 65 %>
        </div>
      </div>
      <div class="flex items-center">
        <%= link_to users_profile_path(article_preview.user.id) do %>
          <%= gravatar_image_tag article_preview.user.email, class:"w-10 h-10 rounded-full mr-4" %>
        <% end %>
        <div class="text-sm">
          <%= link_to users_profile_path(article_preview.user.id) do %>
            <p class="text-gray-900 leading-none"><%= article_preview.user.username %></p>
          <% end %>
          <p class="text-gray-600"><%= time_ago_in_words article_preview.updated_at %></p>
        </div>
      </div>
    </div>
</div>

app/views/articles/_article_preview_alt.erb
<div class="max-w-sm rounded overflow-hidden shadow-xl lg:w-1/4 md:w-1/3 sm:w-1/2 xs:w-full my-16">
  <img class="w-full" src="<%= image_path('header.jpg')%>" alt="Sunset in the mountains">
  <div class="px-6 py-4">
    <div class="font-bold text-xl mb-2">
      <%= link_to article_preview_alt do %>
        <%= article_preview_alt.title %>
      <% end %>
    </div>
    <p class="text-gray-700 text-base">
      <%= truncate strip_tags(article_preview_alt.content.to_s), length: 65 %>
    </p>
  </div>
  <div class="flex items-center my-3 mx-4">
    <%= link_to users_profile_path(article_preview_alt.user), class:"text-gray-900 leading-none font-semibold" do %>
      <%= gravatar_image_tag article_preview_alt.user.email, class:"w-10 h-10 rounded-full mr-4" %>
    <% end %>
    <div class="text-sm">
      <%= link_to users_profile_path(article_preview_alt.user), class:"text-gray-900 leading-none font-semibold" do %>
        <%= article_preview_alt.user.username %>
      <% end %>
      <p class="text-gray-600"><%= time_ago_in_words article_preview_alt.updated_at %></p>
    </div>
  </div>
  <div class="px-6 py-4">
    <% article_preview_alt.categories.each do |category|%>
      <span class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2" style="<% "background-color: #{category.color};" %>">
        <%= link_to category.title, category%>
      </span>
    <% end %>
  </div>
</div>

app/views/articles/_form.html.erb
<%= stylesheet_link_tag "mentions" %>
<div class="container">
  <div class="bg-white my-8 p-5 rounded-lg shadow-lg">
    <div class="flex justify-center">
      <h2 class="font-semibold text-indigo-600 text-4xl mb-4"><%= title %></h2>
    </div>
    <%= form_with(model: @article, local:true) do |form| %>
      <div>
        <%= form.text_field :title, placeholder: :title, class:"appearance-none border border-gray-400 placeholder-gray-800 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>

      <div>
        <%= form.rich_text_area :content, data: { controller: "mentions", target: "mentions.field" }%>
      </div>

      <div class="flex border bg-gray-100 my-3">
        <span class="bg-gray-200 py-1 px-2 font-bold text-medium text-gray-600">#</span><%= form.text_field :tags, placeholder:"Tags", class:"py-1 px-3 placeholder-gray-800"%>
      </div>

      <div>
        <%= form.label "Select a Category:", class:"text-gray-800 font-semibold" %>
        <%= select "article", "category_ids", @categories.collect {|p| [ p.title, p.id]}, {:class => 'block appearance-none w-full bg-gray-200 border border-gray-400 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500' } %>
      </div>
      <div class="flex">
        <%= form.submit :class => 'block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<%= content_for :title, "#{@article.title}" %>
<%= render "shared/navbar" %>
<%= render :partial => "articles/form", :locals => {title: "Edit your Article"}%>
<%= render "shared/footer" %>

app/views/articles/index.html.erb
<%= render "shared/navbar" %>
<div class="container">
  <h1 class="display-4">Articles</h1>
</div>
<%= render @articles %>
<%= render "shared/footer" %>

app/views/articles/new.html.erb
<%= content_for :title, "New Article" %>
<%= render "shared/navbar" %>
<%= render :partial => "articles/form", :locals => {title: "Create an Article"} %>
<%= render "shared/footer" %>

app/views/articles/show.html.erb
<%= content_for :title, @article.title %>
<%= render "shared/navbar" %>
<div class="container mx-auto my-5">
  <%= render @article %>
  <div class="mx-2 my-5">
    <h3 class="text-2xl text-gray-700 font-semibold">
      Comments
    </h3>
  </div>
  <%= render(:partial => "comments/comment", :collection => @comments) || render(partial: "comments/not_found_comments", locals: {message: "This article doesn't have comments.", subtitle: "Be the first to comment!"}) %>
  <%= render "comments/form" %>
</div>
<%= render "shared/footer" %>