config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :questions
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get '/explore', to: 'home#explore'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  resources :mentions, only: [:index]
  resources :categories

  resources :articles do
    resources :comments, only: %w[create destroy]
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  namespace :users do
    get '/:id', to: 'profile#show', as: :profile
  end

  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_alert.html.erb
<div class="bg-yellow-100 p-4" id="banner">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clip-rule="evenodd"></path>
      </svg>
    </div>
    <div class="ml-3">
      <div class="text-sm leading-5 text-yellow-700 font-semibold">
        <p>
          <%= alert %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_error.html.erb
<div class="bg-red-100 p-4" id="banner">
  <div class="flex">
    <div class="flex-shrink-0 text-red-700">
      <i class="fas fa-times-circle fa-lg"></i>
    </div>
    <div class="ml-3">
      <div class="text-sm leading-5 text-red-700 font-semibold">
        <ul>
          <% resource.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="bg-gray-900">
    <div class="max-w-screen-xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
      <div class="xl:grid xl:grid-cols-3 xl:gap-8">
        <div class="xl:col-span-1">
          <%= link_to root_path, class:"flex justify-center lg:hidden xl:flex" do %>
            <%= image_tag "tufd-logo-alt-inverted.svg", class: "w-1/2" %>
          <% end %>
          <p class="mt-8 text-gray-300 text-sm leading-6">
            Learn and share knowledge. Created by Manuel Diaz from WinT 3794. Developed using <%= link_to "Ruby on Rails", 'https://rubyonrails.org/', target:"_blank" %>, <%= link_to "VueJS", 'https://vuejs.org/', target:"_blank" %>, <%= link_to "Tailwind", 'https://tailwindcss.com/', target:"_blank" %>, <%= link_to "Icons8", 'https://icons8.com/', target:"_blank" %>, <%= link_to "FontAwesome", "https://fontawesome.com/", target:"_blank" %>, <%= link_to "SVG Backgrounds", "http://SVGBackgrounds.com", target: "_blank" %> and other open source projects.
          </p>
          <div class="mt-8 flex justify-center">
            <%= link_to 'https://www.facebook.com/WinT3794FRC', target:"_blank", class:"ml-6 text-gray-400 hover:text-gray-500" do %>
              <span class="sr-only">Facebook</span>
              <i class="fab fa-facebook fa-lg"></i>
            <% end %>

            <%= link_to 'https://twitter.com/WinT_frc3794', target:"_blank", class:"ml-6 text-gray-400 hover:text-gray-500" do %>
              <span class="sr-only">Twitter</span>
              <i class="fab fa-twitter fa-lg"></i>
            <% end %>

            <%= link_to 'https://www.instagram.com/wint.3794/', target:"_blank", class:"ml-6 text-gray-400 hover:text-gray-500" do %>
              <span class="sr-only">Instagram</span>
              <i class="fab fa-instagram fa-lg"></i>
            <% end %>

            <%= link_to 'https://github.com/WinT-3794', target:"_blank", class:"ml-6 text-gray-400 hover:text-gray-500" do %>
              <span class="sr-only">GitHub</span>
              <i class="fab fa-github fa-lg"></i>
            <% end %>
          </div>
        </div>
        <div class="mt-12 grid grid-cols-2 gap-8 xl:mt-0 xl:col-span-2">
          <div class="md:grid md:grid-cols-2 md:gap-8">
            <div>
              <h4 class="text-sm leading-5 font-semibold tracking-wider text-gray-400 uppercase">
                Articles
              </h4>
              <ul class="mt-4">
                <li>
                  <%= link_to "Categories", categories_path, class:"text-base leading-6 text-gray-300 hover:text-white" %>
                </li>
                <li class="mt-4">
                  <%= link_to "Teams", "#", class:"text-base leading-6 text-gray-300 hover:text-white" %>
                </li>
                <li class="mt-4">
                  <%= link_to "Newest", "#", class:"text-base leading-6 text-gray-300 hover:text-white" %>
                </li>
                <li class="mt-4">
                  <%= link_to "Popular", "#", class:"text-base leading-6 text-gray-300 hover:text-white" %>
                </li>
              </ul>
            </div>
            <div class="mt-12 md:mt-0">
              <h4 class="text-sm leading-5 font-semibold tracking-wider text-gray-400 uppercase">
                Support
              </h4>
              <ul class="mt-4">
                <li>
                  <a class="text-base leading-6 text-gray-300 hover:text-white" href="#">Pricing</a>
                </li>
                <li class="mt-4">
                  <a class="text-base leading-6 text-gray-300 hover:text-white" href="#">Testimonials</a>
                </li>
                <li class="mt-4">
                  <a href="#" target="_blank" class="text-base leading-6 text-gray-300 hover:text-white">
                    Help Center
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="md:grid md:grid-cols-2 md:gap-8">
            <div>
              <h4 class="text-sm leading-5 font-semibold tracking-wider text-gray-400 uppercase">
                Company
              </h4>
              <ul class="mt-4">
                <li>
                  <a class="text-base leading-6 text-gray-300 hover:text-white" href="/about">About</a>
                </li>
                <li class="mt-4">
                  <a class="text-base leading-6 text-gray-300 hover:text-white" href="/blog">Blog</a>
                </li>
                <li class="mt-4">
                  <a target="_blank" class="text-base leading-6 text-gray-300 hover:text-white" href="#">Podcast</a>
                </li>
              </ul>
            </div>
            <div class="mt-12 md:mt-0">
              <h4 class="text-sm leading-5 font-semibold tracking-wider text-gray-400 uppercase">
                Legal
              </h4>
              <ul class="mt-4">
                <li class="mt-4">
                  <a class="text-base leading-6 text-gray-300 hover:text-white" href="/privacy">Privacy</a>
                </li>
                <li class="mt-4">
                  <a class="text-base leading-6 text-gray-300 hover:text-white" href="/terms">Terms</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="mt-12 border-t border-gray-700 pt-8">
        <p class="text-base leading-6 text-gray-400 xl:text-center">
          © <%= Date.today.year %> WinT 3794. All rights reserved. Under MIT license.
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<title><%= yield :title %> - The Unofficial FIRST Documentation</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= favicon_link_tag "tufd-logo.svg" %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/shared/_navbar.html.erb
<header>
  <nav class="bg-gray-900" id="navbar" x-data="{ open: false }">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
      <div class="relative flex items-center justify-between h-16">
        <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
          <button class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:bg-gray-700 focus:text-white transition duration-150 ease-in-out" @click="open = !open">
            <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24" x-show="!open">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
            </svg>
            <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24" x-show="open">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
            </svg>
          </button>
        </div>
        <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
          <div class="flex-shrink-0">
            <%= link_to root_path do %>
              <%= image_tag 'tufd-logo.svg', class:"block lg:hidden h-8 w-auto", alt:"TUFD Logo" %>
              <%= image_tag 'tufd-logo-alt.svg', class:"hidden lg:block h-8 w-auto", alt:"TUFD Logo" %>
            <% end %>
          </div>
          <div class="hidden sm:block sm:ml-6">
            <div class="flex">
              <%
                @active_url_class = "ml-4 inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-gray-800 hover:bg-gray-700 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150"
                @url_class = "ml-4 px-3 py-2 rounded-md text-sm font-medium leading-5 text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out"
              %>

              <%= link_to "Dashboard", root_path, class: current_page?(root_path) ? @active_url_class : @url_class %>
              <%= link_to "Explore", explore_path, class: current_page?(explore_path) ? @active_url_class : @url_class %>
              <%= link_to "Q&A", questions_path, class: current_page?(questions_path) ? @active_url_class : @url_class %>
              <a href="#" class="ml-4 px-3 py-2 rounded-md text-sm font-medium leading-5 text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out">Forum</a>
              <a href="#" class="ml-4 px-3 py-2 rounded-md text-sm font-medium leading-5 text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out">Calendar</a>
            </div>
          </div>
        </div>
        <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
          <% if user_signed_in? %>
            <%= link_to new_article_path, class:"hidden md:inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150 mx-4" do %>
              Create
              <div class="mx-1">
                <i class="fas fa-plus"></i>
              </div>
            <% end %>
          <% end %>

          <button class="p-1 border-2 border-transparent text-gray-400 rounded-full hover:text-white focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out">
            <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
            </svg>
          </button>

          <div class="ml-3 relative" x-data="{ profileOpen: false }">
            <div>
                <% if user_signed_in? %>
                  <button class="flex text-sm border-2 border-transparent rounded-full focus:outline-none focus:border-white transition duration-150 ease-in-out" @click="profileOpen = !profileOpen">
                    <%= gravatar_image_tag current_user.email, class:"relative z-10 block h-8 w-8 rounded-full" %>
                  </button>
                <% else %>
                <%= link_to "Log in", new_user_session_path, class:"inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150" %>
                <% end %>
            </div>
            <% if user_signed_in? %>
                <div class="origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg z-20" @click.away="profileOpen = false" x-show="profileOpen" x-transition:enter="transition ease-out duration-100" x-transition:enter-start="transform opacity-0 scale-95" x-transition:enter-end="transform opacity-100 scale-100" x-transition:leave="transition ease-in duration-75" x-transition:leave-start="transform opacity-100 scale-100" x-transition:leave-end="transform opacity-0 scale-95">
                  <div class="py-1 rounded-md bg-white shadow-xs">
                    <%= link_to "Your Profile", users_profile_path(current_user.slug), class: "block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-indigo-200 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
                    <%= link_to "Create Article", new_article_path, class: "block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-indigo-200 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
                    <%= link_to "Settings", edit_user_registration_path, class:"block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-indigo-200 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
                    <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"block px-4 py-2 text-sm leading-5 text-gray-700 hover:bg-indigo-200 focus:outline-none focus:bg-gray-100 transition duration-150 ease-in-out" %>
                  </div>
                </div>
            <% end %>

          </div>
        </div>
      </div>
    </div>
      <div class="sm:hidden" x-show="open" x-transition:enter="transition-transform transition-opacity ease-out duration-300" x-transition:enter-start="opacity-0 transform -translate-y-2" x-transition:enter-end="opacity-100 transform translate-y-0" x-transition:leave="transition ease-in duration-300" x-transition:leave-end="opacity-0 transform -translate-y-3">
        <div class="px-2 pt-2 pb-3">
          <%
            @active_url_class_alt = "block px-3 py-2 rounded-md text-base font-medium text-white bg-gray-900 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out"
            @url_class_alt = "mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out"
          %>
          <%= link_to "Dashboard", root_path, class: current_page?(root_path) ? @active_url_class_alt : @url_class_alt %>
          <%= link_to "Explore", explore_path, class: current_page?(explore_path) ? @active_url_class_alt : @url_class_alt %>
          <a href="#" class="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out">Projects</a>
          <a href="#" class="mt-1 block px-3 py-2 rounded-md text-base font-medium text-gray-300 hover:text-white hover:bg-gray-700 focus:outline-none focus:text-white focus:bg-gray-700 transition duration-150 ease-in-out">Calendar</a>
        </div>
      </div>
  </nav>
</header>

app/views/shared/_not_found.html.erb
<div class="flex justify-center">
  <%= image_tag "page-not-found.png", class:"w-full lg:w-1/3", alt:"Image extracted from https://iconos8.es" %>
</div>
<div class="flex justify-center">
  <p class="font-semibold text-3xl text-indigo-700 text-center">
    <%= message %>
  </p>
</div>

app/views/shared/_notice.html.erb
<div class="bg-green-100 p-4" id="banner" x-data="{ bannerOpen: true }" x-show="bannerOpen">
  <div class="flex">
    <div class="flex-shrink-0">
      <svg class="h-5 w-5 text-green-400" fill="currentColor" viewBox="0 0 20 20">
        <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
      </svg>
    </div>
    <div class="ml-3">
      <p class="text-sm leading-5 font-semibold text-green-900">
        <%= notice %>
      </p>
    </div>
    <div class="ml-auto pl-3">
      <div class="-mx-1.5 -my-1.5">
        <button @click="bannerOpen = false" class="inline-flex rounded-md p-1.5 text-green-500 hover:bg-green-100 focus:outline-none focus:bg-green-100 transition ease-in-out duration-150">
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %>">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>